#!/usr/bin/env ruby

require 'bundler/setup'
Bundler.require(:default)

require_all File.join(__dir__, 'lib')

config_path = File.join(__dir__, 'config', 'issue_handlers.yml')
config = ConfigData.new(config_path)

github = IssueHandlers::Github.new(config['github'])
bitbucket = IssueHandlers::Bitbucket.new(config['bitbucket'])

begin
  bitbucket.read_all.each { |i| github.create(i) }
rescue Github::Error::Unauthorized
  abort('Could not authorize to GitHub!')
rescue Github::Error::NotFound
  abort("GitHub repository \"#{github.repository}\" not found!")
rescue BitBucket::Error::Unauthorized
  abort('Could not authorize to Bitbucket!')
rescue BitBucket::Error::NotFound
  abort("Bitbucket repository \"#{bitbucket.repository}\" not found!")
end
