#!/usr/bin/env ruby

require 'bundler/setup'
Bundler.require(:default)

require './lib/issue_handlers/bitbucket'
require './lib/issue_handlers/github'

github_config = YAML.load_file('config/github.yml')
bitbucket_config = YAML.load_file('config/bitbucket.yml')

github = IssueHandlers::Github.new(github_config)
bitbucket = IssueHandlers::Bitbucket.new(bitbucket_config)

bitbucket.read_all_as_github.each { |i| github.create(i) }
